version: '2'

services:

  webserver:
    image: nginx:alpine
    container_name: symfony-webserver
    volumes:
        - ./:/var/www/html
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8888:80"
    links:
      -  php-fpm

  php-fpm:
    build: ./docker/php-fpm
    container_name: symfony-php-fpm
    working_dir: /var/www/html
    links:
      - db
    volumes:
      - symfony-sync:/var/www/html:nocopy

  redis:
    image: redis:alpine
    container_name: symfony-redis
    ports:
        - 6379:6379

  db:
    image: mariadb:10.0.30
    container_name: symfonyedu-mariadb
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=symfony
      - MYSQL_USER=symfony
      - MYSQL_PASSWORD=symfony

volumes:
  symfony-sync:
    external: true